# Generated by Django 4.1.2 on 2022-10-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cancha', models.CharField(choices=[('Tenis de campo', 'Tenis de campo'), ('Baloncesto', 'Baloncesto'), ('Voleibol', 'Voleibol'), ('Futbol Sala', 'Futbol Sala')], max_length=20)),
                ('material', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
                ('tamano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ocupaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=45)),
                ('carrera', models.CharField(max_length=45)),
                ('persona_exterior', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('numero_de_celular', models.BigIntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('tipo_de_ocupacion', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=30)),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ocupaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(choices=[('SI', 'Si'), ('NO', 'NO')], default='SI', max_length=2)),
                ('fecha_reserva', models.DateTimeField()),
                ('canchas_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canchas')),
                ('personas_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Implementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balon', models.SmallIntegerField()),
                ('red', models.CharField(max_length=10)),
                ('arco', models.CharField(max_length=10)),
                ('codigo_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canchas')),
            ],
        ),
    ]
